version: '3.1'
services:
  db:
    image: postgres:12.3
    working_dir: /var/lib/postgresql/backup
    env_file:
      - .env.pg
    environment:
      POSTGRES_DB: cacaomovil
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./storage:/var/lib/postgresql/backup

  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./unicorn.sh
    volumes:
      - .:/app
      - cache:/tmp
    env_file:
      - .env.ruby
    ports:
      - "3030:3000"
    depends_on:
      - db

volumes:
  db:
  cache: