version: '3.1'
services:
  db:
    image: postgres:12.5
    env_file:
      - .env.pg
    ports:
      - "5440:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./storage:/var/lib/postgresql/backup

  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3030:3000"
    env_file:
      - .env.ruby
    command: ./unicorn.sh
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - cache:/tmp
    depends_on:
      - db

  php:
    image: lwr:yii2-74-apache-ga
    ports:
      - '83:80'
    volumes:
      - ../cacaomovil-web/:/app
      - ./public/uploads/:/var/www/uploads
    env_file:
      - .env.php

volumes:
  db:
  cache: